from typing import List, Optional

from pydantic import BaseModel, Field

from app.schemas.llm_schemas import FinalKeywordHierarchy, LLMTokenMetrics, GoogleAdsSettings
from app.schemas.web_crawler_schemas import CrawlStats


# --- API Orchestrator Output Model ---
class AIScanResponse(BaseModel):
    """
    The complete, unified response model for the AI Scan API endpoint.
    """
    structured_data: List[FinalKeywordHierarchy] = Field(
        ...,
        description="The final keyword hierarchy generated by the LLM pipeline."
    )
    # NEW: Expose the detected configuration
    google_ads_config: Optional[GoogleAdsSettings] = Field(
        None,
        description="The recommended Google Ads Geo and Language settings detected from the site."
    )
    crawl_stats: CrawlStats = Field(
        ...,
        description="Detailed statistics and metadata from the web crawling phase."
    )
    llm_metrics: LLMTokenMetrics = Field(
        ...,
        description="Detailed token and time metrics for the entire LLM processing pipeline."
    )