from typing import List

from pydantic import BaseModel, Field

from app.schemas.llm_schemas import FinalKeywordHierarchy, LLMTokenMetrics
from app.schemas.web_crawler_schemas import CrawlStats


# --- API Orchestrator Output Model ---
class AIScanResponse(BaseModel):
    """
    The complete, unified response model for the AI Scan API endpoint.
    Combines the final structured keyword hierarchy with all operational metrics.
    """
    structured_data: List[FinalKeywordHierarchy] = Field(
        ...,
        description="The final keyword hierarchy (categories, groups, keywords) generated by the LLM pipeline."
    )
    crawl_stats: CrawlStats = Field(
        ...,
        description="Detailed statistics and metadata from the web crawling phase."
    )
    llm_metrics: LLMTokenMetrics = Field(
        ...,
        description="Detailed token and time metrics for the entire LLM processing pipeline."
    )
