"""Add applied_labels to Keyword Group and Category

Revision ID: 105846b91f6c
Revises: cf62567791cc
Create Date: 2025-12-12 20:50:59.206394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '105846b91f6c'
down_revision = 'cf62567791cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('applied_labels', sa.JSON(), nullable=True))
    op.add_column('group', sa.Column('applied_labels', sa.JSON(), nullable=True))
    op.add_column('keyword', sa.Column('applied_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'applied_labels')
    op.drop_column('group', 'applied_labels')
    op.drop_column('category', 'applied_labels')
    # ### end Alembic commands ###
