"""Add project hierarchy and refactor linking

Revision ID: 697801231087
Revises: 5fd8955bf14b
Create Date: 2025-12-12 16:52:44.286096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '697801231087'
down_revision = '5fd8955bf14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('google_campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('linked_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'linked_customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('linked_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project', 'linked_customer_id')
    op.drop_column('category', 'google_campaign_id')
    # ### end Alembic commands ###
