"""Fix user routes and models

Revision ID: 78b1569844af
Revises: cde4fbeb42ab
Create Date: 2025-12-01 16:56:23.898449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78b1569844af'
down_revision = 'cde4fbeb42ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
