"""Add applied_labels to Group and Keyword

Revision ID: cf62567791cc
Revises: 697801231087
Create Date: 2025-12-12 20:41:22.560877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf62567791cc'
down_revision = '697801231087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
